Stat.create(
	game_date:       'Wed 10/4', 
    opp:             'vsMEM',
    score:           'n/a',
    min:             'n/a',   
    fgm_fga:         'n/a',    
    fg_prct:         'n/a',    
    three_m_a:       'n/a',
    three_prct:      'n/a',  
    ftm_fta:         'n/a',     
    ft_prct:         'n/a',     
    reb:             'n/a',        
    ast:             'n/a',        
    blk:             'n/a',         
    stl:             'n/a',         
    pts:             'n/a',
    video_id:        'oG9o_1FbzGU',
    player_giphy_id: 'alaGWsSrlo1Gw',
    game_giphy_id:    ''
)
